"""Guard against internal planning identifiers in tracked text.

Planning shorthand (wave.item ids, work-order ids, debt-register ids,
UX-workstream ids, "Wave N" word forms, wave-round ids, and lettered
finding ids) belongs in planning documents only. The owner's rule, quoted
verbatim in the failure message below, is that these must never appear in
code, comments, docs, test names, or any other text this repository ships.
A sweep of this repository found zero instances; this module exists so a
new one can never land without failing the suite.

Provenance belongs in decision-record paths or version numbers instead.

Adaptations for this repository (the rule originated in a TypeScript
codebase and is re-expressed here in this repo's own vocabulary):

* ``Z-Wave 700``-style hardware names are genuine Home Assistant
  vocabulary, so the "Wave <digits>" pattern excludes anything preceded
  by ``Z-``/``z-``.
* Bluetooth/BLE MAC address strings such as ``"A4:C1:38:2B:11:7F"`` start
  with a capital letter, two hex digits, and a colon — the same opening
  as a "finding-id title" string. The title form therefore requires
  whitespace after the colon, which titles have and MAC addresses do not.
* Lettered finding ids are only banned in three unambiguous shapes
  (alone in parentheses; at the start of a test/describe/it title or a
  Python docstring, followed by a colon-plus-space or an em dash; two or
  more chained by forward slashes). The bare token in running text is NOT
  banned: hex bytes, serial numbers, quoted-printable escapes, and base64
  material all legitimately contain letter-plus-digit tokens.

Exemptions (see ``EXEMPT_FILES`` / ``EXEMPT_PREFIXES``):

* this test module itself — it must spell out the banned shapes as
  fixture data to pin the patterns' behavior;
* ``frontend/package-lock.json`` — machine-generated by npm; its base64
  integrity hashes can collide with the slash-chained finding-id shape
  and the file is never hand-written text.
"""

from __future__ import annotations

import pathlib
import re
import subprocess

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]

OWNER_DOCTRINE = (
    "never put wave/work-order/register ids in outward-facing or in-code text; "
    "plain language only; provenance via decision-record paths or versions"
)

# Files exempt from the repository scan, as repo-relative POSIX paths.
EXEMPT_FILES = frozenset(
    {
        # This module: holds the banned shapes as fixture data on purpose.
        "tests/test_no_internal_identifiers.py",
        # npm lockfile: machine-generated; base64 integrity hashes can
        # collide with the slash-chained finding-id shape.
        "frontend/package-lock.json",
    }
)

# Directory prefixes exempt from the repository scan (repo-relative, POSIX,
# trailing slash). None today; the mechanism exists for future legitimate
# carve-outs such as dated, self-contained historical release records.
EXEMPT_PREFIXES: tuple[str, ...] = ()

_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (
        re.compile(r"\bW[0-9]{1,2}\.[0-9]{1,2}\b"),
        "wave.item id (capital W, digits, dot, digits)",
    ),
    (
        re.compile(r"\bwo[0-9]{3,4}\b", re.IGNORECASE),
        'numeric work-order id ("wo" followed by 3-4 digits)',
    ),
    (
        re.compile(r"\bWO-[A-Z]\b"),
        'lettered work-order id ("WO-" plus one capital letter)',
    ),
    (
        re.compile(r"\bWO-[0-9]{2,4}\b"),
        'numbered work-order id ("WO-" plus 2-4 digits)',
    ),
    (
        re.compile(r"\bDEBT-[0-9]+\b"),
        'debt-register id ("DEBT-" plus digits)',
    ),
    (
        re.compile(r"\bUX-[A-Z]\b"),
        'UX-workstream id ("UX-" plus one capital letter)',
    ),
    (
        # (?<![Zz]-) spares Z-Wave hardware names like "Z-Wave 700 series".
        re.compile(r"(?<![Zz]-)\bWave[- ][0-9]+\b"),
        'wave word form ("Wave" plus hyphen or space plus digits)',
    ),
    (
        re.compile(r"\bW[0-9]+-R[0-9]+\b"),
        "wave-round id (capital W, digits, hyphen, capital R, digits)",
    ),
    (
        # F is excluded from the letter range: F-plus-digits is a function
        # key, genuine technical vocabulary.
        re.compile(r"\([A-E][0-9]{1,2}\)"),
        "lettered finding id alone inside parentheses",
    ),
    (
        re.compile(r"\b(?:describe|test|it)\(\s*['\"][A-E][0-9]{1,2}\s*(?::|—)"),
        "JS test title starting with a lettered finding id",
    ),
    (
        # The colon must be followed by whitespace so MAC-address strings
        # such as "A4:C1:38:2B:11:7F" at the start of a line do not match.
        re.compile(r"^\s*(?:\"\"\"|'''|\"|')[A-E][0-9]{1,2}\s*(?::\s|—)"),
        "Python docstring or string title starting with a lettered finding id",
    ),
    (
        re.compile(r"\b[A-E][0-9]{1,2}(?:/[A-E][0-9]{1,2})+\b"),
        "lettered finding ids chained by forward slashes",
    ),
)


def find_internal_identifiers(text: str) -> list[tuple[int, str, str]]:
    """Return (line number, matched token, pattern description) per hit.

    At most one hit is reported per line — enough to locate and fix it.
    """

    hits: list[tuple[int, str, str]] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        for pattern, description in _PATTERNS:
            match = pattern.search(line)
            if match:
                hits.append((lineno, match.group(0), description))
                break
    return hits


def _tracked_files() -> list[str]:
    """Repo-relative POSIX paths of every git-tracked file."""

    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return [path for path in result.stdout.split("\0") if path]


def test_tracked_text_is_free_of_internal_identifiers():
    """No tracked text file may contain an internal planning identifier."""

    violations: list[str] = []
    for rel_path in _tracked_files():
        if rel_path in EXEMPT_FILES or rel_path.startswith(EXEMPT_PREFIXES):
            continue
        try:
            text = (REPO_ROOT / rel_path).read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue  # binary asset (e.g. the brand icon)
        for lineno, token, description in find_internal_identifiers(text):
            violations.append(f'{rel_path}:{lineno}: {description}: "{token}"')

    assert not violations, (
        "Internal planning identifiers found in tracked text — "
        f"{OWNER_DOCTRINE}:\n" + "\n".join(violations)
    )


@pytest.mark.parametrize(
    "line",
    [
        pytest.param(
            "resolved as part of W3.4 alongside the coordinator rework",
            id="wave-item-id",
        ),
        pytest.param(
            "tracked as wo1234 in the planning journal", id="numeric-work-order"
        ),
        pytest.param(
            "follow-up: WO-C covers the reconnect path", id="lettered-work-order"
        ),
        pytest.param(
            "follow-up: WO-17 covers the reconnect path", id="numbered-work-order"
        ),
        pytest.param(
            "carried as DEBT-9 until the payload split lands", id="debt-register-id"
        ),
        pytest.param("the UX-B pass reworked the panel header", id="ux-workstream-id"),
        pytest.param(
            "shipped in Wave 3 of the platform cycle", id="wave-word-space"
        ),
        pytest.param(
            "shipped in Wave-3 of the platform cycle", id="wave-word-hyphen"
        ),
        pytest.param("queued for W2-R4 review", id="wave-round-id"),
        pytest.param(
            "fixed the stale entity id (B7) by refreshing the registry",
            id="parenthesized-finding-id",
        ),
        pytest.param(
            'it("C3: reconnects after the daemon restarts", async () => {',
            id="js-test-title-finding-id",
        ),
        pytest.param(
            '    """D4: verifies the watchdog reconnects."""',
            id="python-docstring-finding-id",
        ),
        pytest.param("covers A1/B2/C3 from the review", id="slash-chained-finding-ids"),
    ],
)
def test_violation_shapes_are_flagged(line: str):
    """Every banned identifier shape must be detected."""

    assert find_internal_identifiers(line), (
        f"expected the check to flag: {line!r}"
    )


@pytest.mark.parametrize(
    "line",
    [
        pytest.param(
            "sensor.living_room_temperature reports the current reading",
            id="ha-entity-id",
        ),
        pytest.param('    "A4:C1:38:2B:11:7F",', id="ble-mac-address-string"),
        pytest.param(
            "ieee address 00:15:8d:00:02:bf:6b:d2 for the zigbee sensor",
            id="zigbee-ieee-address",
        ),
        pytest.param(
            "quoted-printable em dash =E2=80=94 in the payload",
            id="quoted-printable-escape",
        ),
        pytest.param(
            '"integrity": "sha512-AbC4dEfG9hIjKlMnOpQrStUvWxYz0123456789=="',
            id="base64-integrity-hash",
        ),
        pytest.param(
            "press F1 for help; F12 opens the browser devtools",
            id="function-keys-f-excluded",
        ),
        pytest.param(
            "the Z-Wave 700 series controller pairs over the stick",
            id="z-wave-hardware-name",
        ),
        pytest.param("validated against SDK 1.7.1", id="version-number"),
        pytest.param(
            "Home Assistant 2026.2.3 is the pinned test baseline",
            id="calver-version",
        ),
        pytest.param(
            "firmware SW1.2 shipping on the hub", id="firmware-revision-token"
        ),
        pytest.param(
            '"""B2B daemon payloads round-trip unchanged."""',
            id="docstring-word-starting-letter-digit",
        ),
    ],
)
def test_legitimate_technical_tokens_are_not_flagged(line: str):
    """Genuine technical tokens that resemble the shapes must pass."""

    assert find_internal_identifiers(line) == [], (
        f"expected the check to allow: {line!r}"
    )
